version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.0
